name: Secure CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scanning:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run npm audit
      - name: Run npm audit
        run: npm audit

      # Secret Scanning - TruffleHog
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

      # Static Analysis with ESLint
      - name: Install ESLint
        run: |
          npm install eslint eslint-plugin-security
          npx eslint --init

      - name: Run ESLint
        run: npx eslint . --ext .js

  policy-compliance:
    name: Policy Compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Open Policy Agent
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod 755 opa
          sudo mv opa /usr/local/bin/

      - name: Run OPA Policy Checks
        run: |
          opa eval --data policies/security.rego --input policies/input.json "data.security.allow" 